[project]
name = "old-movie"
version = "0.1.0"
description = "Generates shaky video title cards in an old-movie style"
readme = "README.md"
authors = [
    { name = "Alberto Caro", email = "alberto.caro.m@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "click>=8.1",
    "pillow>=12.3.0",
]

[project.scripts]
old-movie = "old_movie:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
